Python One-Liners

In [ ]:
import numpy as np

1. insert the correct code for creating a numpy array

In [ ]:
a = np.array([1, 2, 3, 4, 5]) # use np
print(a)

[1 2 3 4 5]


2. consider this function:

In [ ]:
def what(n):
  a = np.array([1, 2, 3, 4], ndmin=n)
  print(a.ndim)
  return a


 what is the difference between what(1), what(2) and what(3)

In [ ]:
print(what(1)) # what do these print and why?
print(what(2))
print(what(3))

#1    #One dimentional
#[1 2 3 4]
#2    #wo-dimentional
#[[1 2 3 4]]
#3    # three-dimentional
#[[[1 2 3 4]]]

#Array got one and passes one,so one dimentional,
#then pass two, so two-dimentional, etc.

1
[1 2 3 4]
2
[[1 2 3 4]]
3
[[[1 2 3 4]]]


 3. insert the correct argument for creating a numpy array with 2 dimensions


In [ ]:
a = np.array([1, 2, 3, 4], ndmin=2 )
print(a)

[[1 2 3 4]]


4. insert the correct syntax for checking the number of dimensions of a numpy array

In [ ]:
a = np.array([1, 2, 3, 4])
print( a.ndim )

b = np.array([[1, 2], [3, 4]])
print( b.ndim )

1
2


5. insert the correct syntax for printing the first item in the array:

In [ ]:
a = np.array([1, 2, 3, 4])
print(a[0])

1


6. insert the correct syntax for printing the number 50 from the array

In [ ]:
a = np.array([10, 20, 30, 40, 50])
print( a[4] )

50



7. insert the correct syntax for printing the number 50 from the array



In [ ]:
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print( a[1][0] ) # should print 50 must use a

50



8. use negative indexing to print the last item in the array

In [ ]:
a = np.array([10, 20, 30, 40, 50])
print( a[-1] ) # should print 50 must use a

50


9. slice out everything from the second item to (not including) the fifth item

In [ ]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[1:4]) # should print [15 20 25] must use a

[15 20 25]


10. Slice out everything from the third item to (not including) the fifth item


In [ ]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print( a[2:4] ) # should print [20 25] must use a

[20 25]



11. slice out every other item from the second item to (not including) the fifth item

In [ ]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print( a[1:4:2] ) # should print [15 25] must use a

[15 25]


12. slice out every other item from the entire array


In [ ]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print( a[::2] ) # should print [10 20 30 40] must use a

[10 20 30 40]


13. insert correct syntax to print the datatype of an array



In [ ]:
a = np.array([1, 2, 3])
print( a.dtype ) # should print something indicating this is an array of integers
#int64

int64


14. insert the correct argument to specify that array should be of type STRING



In [ ]:
a = np.array([1, 2, 3, 4], dtype= 'S' )

#     then predict and explain the output for the following expressions

print(a.dtype) #|S1
print(a) #[b'1' b'2' b'3' b'4']

# convert it to stings by using 'S' as a data type

|S1
[b'1' b'2' b'3' b'4']


In [ ]:
print(a[0] + a[1]) #b'12'

#no adittion but concationation
#concatenating byte strings

a = np.array([5, 1, -1, 3], dtype='S')
print(a) # a[b'5' b'1' b'-1' b'3']

b = a.astype('i') # changing data type
                    #converting to the integer array
print(b) #[5,1,-1,3]

print(b[0] + b[1] + b[3]) #9  #adding up integers
print(a[0] + a[1] + a[3]) #b'513' #concatenating byte strings

b'12'
[b'5' b'1' b'-1' b'3']
9
b'513'



15. insert correct method to change data type to integer


In [ ]:
a = np.array([1.1, 2.1, 3.1])
b = a.astype( 'i' )
print(b) # should print [1 2 3] now

[1 2 3]


16. use the correct method to make a copy of the array




In [ ]:
a = np.array([1, 2, 3, 4, 5])
x = np.copy(a) # [1 2 3 4 5]
print(x)

[1 2 3 4 5]


In [ ]:
#     then predict the effect of the following expressions

x[0] = -5
print(a) # does a see the change? #[1 2 3 4 5]
#no change here

b = a
b[0] = -25
print(a) # does a see the change? #[-25   2   3   4   5]
#changed because 'b' is a reference

#yes, there is a change.
#Changing b[0] modifies 'a' as well (they point to the same memory location).

[1 2 3 4 5]
[-25   2   3   4   5]


17. use the correct method to make a view of this array:


In [ ]:
a = np.array([1, 2, 3, 4, 5])
d = a.view()

In [ ]:
#     then predict the effect of these expressions:

print(a.base) #none

print(d.base) # why is this different from all the others?
#different because it references to 'a'

b = a
print(b.base) #none

c = a.copy()
print(c.base) #none

#'base' is pointing at returns the base object if the
# memory of the array is owned by some other object.
# this attribute is used to discover whether an array is
# a view of another base array. If the array owns its memory,
# as is the case with arrays that are not views but are created
# independently, ndarray. base

None
[1 2 3 4 5]
None
None


18.predict (and explain) the outcome of these expressions


In [ ]:
a = np.array([1, 2, 3, 4]) #reshaping it
print(a.shape) # 4 rows and no columns #(4,)

a.reshape(1, 4) #one row 4 columns #[1 2 3 4]
print(a)

a.reshape(2, 2) #two rows and columns  #[1 2 3 4]
print(a)

a.reshape(4, 1) #4 rows and one column  #[1 2 3 4]
print(a)

(4,)
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


19. use the correct numpy method to change the shape of an array from 1-D to 2-D:


In [ ]:
a = np.array([1, 2, 3, 4])
a = a.reshape(2, 2) # write code here must use a
print(a) # must print [[1, 2] [3 4]]

[[1 2]
 [3 4]]


20. use correct numpy method to change shape of an array from 2-D to 1-D


In [ ]:
a = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
b = a.reshape( 12 ) # complete this statement to result in the output below
print(b) # must print [ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


21. use a correct numpy method to join two arrays into a single array


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate([a, b]) # use np, a and b somehow
print(c) # must print [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [ ]:
#     then predict and explain the outcome of the following expressions

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a, b), axis=1)
print(c) # what gets printed and why?

#axis=1 concatenating horizontally
#[[1 2 5 6] [3 4 7 8]]


c  = np.stack((a, b), axis = 0) # what does stack do differently (if anything)?
print(c) #not concatenating but stacking
#three-dimentional

#[[[1 2] [3 4]] #creates a layer and separtes them

# [[5 6] [7 8]]]

[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


22. use correct numpy syntax to find all items with value 4


In [ ]:
a = np.array([1, 2, 3, 4, 5, 4, 4])
where = np.where(a==4) # complete statement, must use np, a and 4
print(where) # must print (array([3, 5, 6]),)

(array([3, 5, 6]),)


23. use the correct numpy method to return a sorted array


In [ ]:
a = np.array([3, 2, 0, 1])
b = np.sort(a) # complete statement, must use np and a
print(b) # must print [0 1 2 3]

[0 1 2 3]


24. Solve exercise 3-1 on page 57:
 How # do we find the person with maximum after-tax income in a group of people,given their yearly salary and tax rates?


In [ ]:
## Data: yearly salary in ($1000) [2017, 2018, 2019]
alice = [ 99, 101, 103]
bob = [110, 108, 105]
tim = [ 90, 88, 85]

names = ['alice','bob','tim' ]
salaries = np.array([alice, bob, tim])
print(salaries)

taxation = np.array([[0.2, 0.25, 0.22],
                     [0.4, 0.5 , 0.5 ],
                     [0.1, 0.2 , 0.1 ]])

#One-liner
max_income = np.max(salaries - salaries * taxation)

## Result
print(max_income)

[[ 99 101 103]
 [110 108 105]
 [ 90  88  85]]
81.0


25. predict and explain the effect of the following expressions


In [ ]:
a = np.array([
              [[1, 2], [3, 4]],
              [[5, 6], [7, 8]]
              ])
#two-dimentional array (matrix)

#average horizontally(layers) or first-dimention
print(np.average(a, axis=0)) # review the meaning of the axis parameter

#calculating vertically(within layers) or second-dimention
print(np.average(a, axis=1))

#avearge across columns or third-dimention
print(np.average(a, axis=2))


[[3. 4.]
 [5. 6.]]
[[2. 3.]
 [6. 7.]]
[[1.5 3.5]
 [5.5 7.5]]


26. predict and explain the effect of the following expressions


In [ ]:
a = np.array([[[ 1,  2,  3], [22,  5,  6], [ 7,  8,  9]],
              [[11, 12, 10], [ 4, 14, 15], [16, 17, 18]],
              [[19, 20, 21], [13, 23, 24], [25, 26, 27]]])

In [ ]:
b = np.sort(a, axis=0)
print(b) # what gets printed and why?
#[[[ 1  2  3] [ 4  5  6] [ 7  8  9]]
# [[11 12 10] [13 14 15] [16 17 18]]
# [[19 20 21] [22 23 24] [25 26 27]]]

c = np.sort(a, axis=1)
print(c)
#[[[ 1  2  3] [ 7  5  6] [22  8  9]]
# [[ 4 12 10] [11 14 15] [16 17 18]]
#[[13 20 21] [19 23 24] [25 26 27]]]

d = np.sort(a, axis=2)
print(d)
#[[[ 1  2  3] [ 5  6 22] [ 7  8  9]]
#[[10 11 12] [ 4 14 15] [16 17 18]]
#[[19 20 21] [13 23 24] [25 26 27]]]

#Basic process is is seprarting it into the layers (1,2, and 3)
#then sorting column-wise into smallest, middle, and largest.
#axis=0, sorts layers vertically
#axis=1, sorts each individual row
#axis=2, sorts each elemnts in the row by itself
#sorts the same row


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 10]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 7  5  6]
  [22  8  9]]

 [[ 4 12 10]
  [11 14 15]
  [16 17 18]]

 [[13 20 21]
  [19 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 5  6 22]
  [ 7  8  9]]

 [[10 11 12]
  [ 4 14 15]
  [16 17 18]]

 [[19 20 21]
  [13 23 24]
  [25 26 27]]]
